services:
  adguard:
    container_name: adguard
    image: ghcr.io/laugmanuel/adguard-home-ha:main
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

    ### For host networking mode ###
    network_mode: host

    ### for IPVlan networking mode ###
    # networks:
    #   macvlan:
    #     ipv4_address: 192.168.0.4

    volumes:
      - ./data/config:/opt/adguardhome/conf
      - ./data/work:/opt/adguardhome/work
    environment:
      TZ: Europe/Berlin
      KEEPALIVED_ENABLED: true
      KEEPALIVED_STATE: BACKUP
      KEEPALIVED_VIP: "192.168.0.2"
      ADGUARD_CONFIG_SYNC_ENABLED: true
      ADGUARD_CONFIG_SYNC_ROLE: FOLLOWER
      ADGUARD_CONFIG_SYNC_PRIMARY_URL: "http://192.168.0.3:2015/AdGuardHome.yaml" # this is the IP of the master instance
    healthcheck:
      test: nslookup k.root-servers.net 127.0.0.1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      autoheal: true

  ## for autohealing ##
  autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal:latest
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

## For MACvlan networking mode ##
# networks:
#   macvlan:
#     external: true
